- title: Basic Web Application by Ring
  permalink: /docs/web-applications/basic-ring/

- title: Easy Web Application by Compojure
  permalink: /docs/web-applications/easy-compojure/

- title: HTML generation by Hiccup
  permalink: /docs/web-applications/hiccup/
