- title: Basic Web Application by Ring
  permalink: /docs/web-applications/basic-ring/
  todo: false

- title: Easy Web Application by Compojure
  permalink: /docs/web-applications/easy-compojure/
  todo: false

